### ISSUE TITLE
Compatibility with themes and fonts from Carolingian UI module

### ISSUE THREAD

**Issue by crlngn** [BragginRites/inspect-statblock#8]
Hi there,

Hi there, I'm the developer of [Carolingian UI](https://foundryvtt.com/packages/crlngn-ui) module, and I would love to collaborate to make our modules work together. 
Among other features, my module gives users the ability to make two customizations to Foundry's default UI: 1) select custom fonts for the whole interface, titles and journals 2) select a color theme that applies colors to elements of the UI, like buttons, titles etc.

For our modules to work together, it would not be too hard. You would simply need to use Foundry's css variables for font-family and color accents. 

--color-warm-2 is the main variable for accents, but for text links you may want to use --color-text-hyperlink. 
If you simple replace your yellow color code with var(--color-main-2); your UI will use default Foundry orange color. If you install my UI module, it will apply whatever theme color the user selected. And if you want to have your yellow as default if my module is not available, you can create a class for the body in which your replace the color that  --color-warm-2 represents.

```css
body.crlngn-ui {
  --color-warm-1: rgb(177, 51, 55);
  --color-warm-2: rgb(152, 33, 37);
  --color-warm-3: rgb(95, 22, 27);  
  --color-scrollbar: rgba(152, 33, 37, 0.7);
  --color-text-hyperlink: rgb(186, 62, 62);
  /* this is a dark secondary color that is not on Foundry, but I apply to certain elements. I have some variations for different opacities as well */
  --color-secondary: rgb(40, 31, 49);
}

```
The example above is for variables and I apply for the 'Royal Blood' theme, with blood red and dark eggplant colors for accents, suitable for Ravenloft for example. 

<img src="https://github.com/crlngn/crlngn-ui/blob/v2/demo/crlngn-ui-2.1-ui.png?raw=true" />
The above is a screenshot for v13, but the same applies to v12.

So you would use something like body.inspect-statblock {} instead of body.crlngn-ui {} and change Foundry variables to use your specific module colors.

For font families, I give users 4 distinct choices:
- General UI font
- UI titles
- Journal font
- Journal titles

```css
body.crlngn-ui {
  --font-body: var(--crlngn-font-family); 
  --font-sans: var(--crlngn-font-family); 
  --font-blockquote: var(--crlngn-font-journal-body);
  --dnd5e-font-roboto-slab: var(--crlngn-font-titles);
  --dnd5e-font-roboto: var(--crlngn-font-family);
  --dnd5e-font-modesto: var(--crlngn-font-journal-title);
}
```
And on my code I define what font --crlngn-font-family is, depending on user choices. 
So you could use --font-body or --font-sans for your UI if you want to be system agnostic, and if users have my module enabled the fonts will be automatically enabled.

Let me know if you would want to apply these changes yourself, or I can send you a PR. The same applies to BG3 Inspired HUD.
Thanks and kudos for the modules :)
